name: Build

on:
  workflow_dispatch:

jobs:
  build_kvlib_linux:
    runs-on: ubuntu-20.04
    steps:
    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build kvlib
      working-directory: ./kvlib
      run: xmake build -y linux
    - name: Upload kvlib
      uses: actions/upload-artifact@v4
      with:
        name: kvlib_linux
        path: kvlib/build/linux/x86_64/release/kvlib.so
  build_kvlib_windows:
    runs-on: windows-latest
    steps:
    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build kvlib
      working-directory: ./kvlib
      run: xmake build -y windows
    - name: Upload kvlib
      uses: actions/upload-artifact@v4
      with:
        name: kvlib_windows
        path: kvlib/build/windows/x64/release/kvlib.dll
  build_dotnet:
    runs-on: windows-latest
    needs: [build_kvlib_linux, build_kvlib_windows]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Prepare kvlib dir
        run: mkdir -p ./kvlib_output
      - name: Download kvlib linux
        uses: actions/download-artifact@v4
        with:
          name: kvlib_linux
          path: ./kvlib_output
      - name: Download kvlib windows
        uses: actions/download-artifact@v4
        with:
          name: kvlib_windows
          path: ./kvlib_output
      - name: Build .NET
        run: dotnet build
      - name: Copy kvlib to plugin
        run: cp ./kvlib_output/* ./build/addons/counterstrikesharp/plugins/SkyboxChanger
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SkyboxChanger
          path: ./build


     




